spring:
  cloud:
    config:
      server:
        git:
          uri: https://github.com/vipul-gorasiya/Spring-MicroServices-OnlineShopping-HSQL-ExternalServer-Config
server:
  port: 5055
  host: INPUHJPC04133